name: The name of your workflow
on [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.https://hooks.slack.com/services/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 }}
        if: always()
  
